name: markdown-autodocs

on:
  push:
    branches:
    pull_request:

jobs:        
  auto-update-programming-guide:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.4
          with:
            output_file_paths: '[./programming_guide/section-1/README.md]'